variable "auth_token" {}
variable "project_id" {}
variable "esx_size" {}
variable "metro" {}
variable "vcf_version" {}
variable "esx_pw" {}
variable "billing_cycle" {}
variable "vlans" {}
variable "esx_names" {}
variable "esx_ips" {}
variable "esx_gateway" {}
variable "esx_subnet" {}
variable "esx_dns" {}
variable "esx_domain" {}
variable "esx_mgmtvlan" {}
variable "esx_ntp" {}
variable "public_ips_net" {}
variable "edge_hostname" {}
variable "edge_size" {}
variable "edge_os" {}
variable "pub_ip" {}
